### ISSUE TITLE
Consult the various methods implemented in the paper

### ISSUE THREAD

**Issue by MAX-OTW** [mhmd-mst/Visual-Geolocation#1]
Hello, @hajalibayram @mhmd-mst @gbarbarani ,-I really appreciate for your work in [the paper](https://openaccess.thecvf.com/content/CVPR2023W/IMW/html/Barbarani_Are_Local_Features_All_You_Need_for_Cross-Domain_Visual_Place_CVPRW_2023_paper.html) ! Congratulations:)

At present, I want to reproduce the various methods mentioned in the paper,but there are some difficulties for me.

Is it convenient for you to provide the implementation of various methods in the paper？I'd appreciate it if you could.

I am always looking forward to your kind response.
Best regards.

**Comment by hajalibayram** [comment]
Hi, @MAX-OTW. Please refer to the issue at https://github.com/gbarbarani/re-ranking-for-VPR/issues/1. Thank you :)
